NomeCliente=input("Digite o nome do cliente")
DiaVencimento=input("Digite o dia do vencimento da fatura")
MesVencimento=input("Digite o mês do vencimento da fatura")
ValorFatura=input("Digite o valor da fatura")
print("Olá,",NomeCliente)
print("A sua fatura com vencimento em",DiaVencimento,"de",MesVencimento,"no valor de R$",ValorFatura,"está fechada.")